# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63e44b3a41a029686d104fe8520218e0050b9baac8988671e89a35fbb0e9be09ed8924030ea4525126b844caab3d573aeac07d94a1421a869ada1448d4d82957

test:
  secret_key_base: 6400e5bbe0ee3af8484984762d8591200b0f0ac52be03ec6407a9c54eab5fd6670328c2b6e6db07884fe689aa72458fdd3014e7353a623eb6b74c591d83f5351

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
